<?php

use App\Model\Workflow;
use App\Model\Workflows;

 $this->headTitle('Home'); ?>

<div class="jumbotron" style="text-align: center;">
    <h1>A simple system for support scripts</h1>
</div>

<div class="row">
<?php
$names = Workflows::getNames();
foreach ($names as $index => $name):
    $workflow = new Workflow($name);
?>
    <div class="col-md-4">
        <h2>
            <a href=<?=$this->url('workflow',['name' => $name, 'path'=>'2'])?>>
                <i class="fa fa-phone"></i> <?=$workflow->getTitle()?>
            </a>
        </h2>
        <p>
            <?=$workflow->getDescription()?>
        </p>
    </div>
<?php
    if (($index + 1) % 3 == 0){
?>
</div>
<div class="row">
<?php
    }
endforeach;
?>
</div>
